# Generated by Django 4.0 on 2026-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options_rename_price_products_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
